export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR' = 'GET_INGREDIENTS_ERROR';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const REORDER_INGREDIENTS: 'REORDER_INGREDIENTS' = 'REORDER_INGREDIENTS';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR: 'GET_ORDER_ERROR' = 'GET_ORDER_ERROR';

export const GET_ORDER_FEED_REQUEST: 'GET_ORDER_FEED_REQUEST' = 'GET_ORDER_FEED_REQUEST';
export const GET_ORDER_FEED_SUCCESS: 'GET_ORDER_FEED_SUCCESS' = 'GET_ORDER_FEED_SUCCESS';
export const GET_ORDER_FEED_ERROR: 'GET_ORDER_FEED_ERROR' = 'GET_ORDER_FEED_ERROR';

export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';

export const LOGIN_USER: 'LOGIN_USER' = 'LOGIN_USER';
export const LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST' = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_ERROR: 'LOGIN_USER_ERROR' = 'LOGIN_USER_ERROR';

export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST' = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_ERROR: 'REGISTER_USER_ERROR' = 'REGISTER_USER_ERROR';

export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR';

export const LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST' = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS' = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR' = 'LOGOUT_USER_ERROR';

export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" = "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" = "WS_CONNECTION_CLOSED";
export const WS_CONNECTION_CLOSE: "WS_CONNECTION_CLOSE" = "WS_CONNECTION_CLOSE";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";

export const USER_WS_CONNECTION_START: "USER_WS_CONNECTION_START" = "USER_WS_CONNECTION_START";
export const USER_WS_CONNECTION_SUCCESS: "USER_WS_CONNECTION_SUCCESS" = "USER_WS_CONNECTION_SUCCESS";
export const USER_WS_CONNECTION_ERROR: "USER_WS_CONNECTION_ERROR" = "USER_WS_CONNECTION_ERROR";
export const USER_WS_CONNECTION_CLOSED: "USER_WS_CONNECTION_CLOSED" = "USER_WS_CONNECTION_CLOSED";
export const USER_WS_CONNECTION_CLOSE: "USER_WS_CONNECTION_CLOSE" = "USER_WS_CONNECTION_CLOSE";
export const USER_WS_GET_MESSAGE: "USER_WS_GET_MESSAGE" = "USER_WS_GET_MESSAGE";
export const USER_WS_SEND_MESSAGE: "USER_WS_SEND_MESSAGE" = "USER_WS_SEND_MESSAGE";


